# Generated by Django 2.0.8 on 2018-08-19 19:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign', models.CharField(help_text='Sign of the currency of exchange. ex: $', max_length=32, verbose_name='Sign')),
                ('code', models.CharField(help_text='Currency code. ex: USD', max_length=32, verbose_name='Code')),
                ('description', models.CharField(blank=True, help_text='Description of currency', max_length=255, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currencies',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(blank=True, max_length=256, verbose_name='Identifier')),
                ('name', models.CharField(max_length=2048, verbose_name='Name')),
                ('description', models.CharField(max_length=4000, verbose_name='Description')),
                ('value', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Value')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paypal_express_checkout.Currency')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creation time')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Time')),
                ('transaction_id', models.CharField(max_length=32, verbose_name='Transaction ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Transaction value')),
                ('status', models.CharField(choices=[('Checkout', 'Checkout'), ('Pending', 'Pending'), ('Canceled', 'Canceled'), ('Completed', 'Completed'), ('Canceled_Reversal', 'Canceled_Reversal'), ('Created', 'Created'), ('Denied', 'Denied'), ('Expired', 'Expired'), ('Failed', 'Failed'), ('Refunded', 'Refunded'), ('Reversed', 'Reversed'), ('Processed', 'Processed'), ('Voided', 'Voided')], max_length=16, verbose_name='Payment status')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.ContentType')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paypal_express_checkout.Currency')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'ordering': ['-creation_date', 'transaction_id'],
            },
        ),
        migrations.CreateModel(
            name='PaymentTransactionError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Time')),
                ('paypal_api_url', models.CharField(blank=True, max_length=4000, verbose_name='Paypal API URL')),
                ('request_data', models.TextField(blank=True, verbose_name='Request data')),
                ('response', models.TextField(blank=True, verbose_name='Response String')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='paypal_express_checkout.PaymentTransaction', verbose_name='Payment transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='PurchasedItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(blank=True, max_length=256, verbose_name='Identifier')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True, verbose_name='Price')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantity')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.ContentType')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='paypal_express_checkout.Item', verbose_name='Item')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paypal_express_checkout.PaymentTransaction', verbose_name='Transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'ordering': ['-transaction__date', 'transaction__transaction_id'],
            },
        ),
    ]
